/*
 * Generated by gdbus-codegen 2.50.3. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "obex_session1_interface.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.bluez.obex.Session1
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:OrgBluezObexSession1
 * @title: OrgBluezObexSession1
 * @short_description: Generated C code for the org.bluez.obex.Session1 D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-bluez-obex-Session1.top_of_page">org.bluez.obex.Session1</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.bluez.obex.Session1 ---- */

static const _ExtendedGDBusArgInfo _org_bluez_obex_session1_method_info_get_capabilities_OUT_ARG_capabilities =
{
  {
    -1,
    (gchar *) "capabilities",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _org_bluez_obex_session1_method_info_get_capabilities_OUT_ARG_pointers[] =
{
  &_org_bluez_obex_session1_method_info_get_capabilities_OUT_ARG_capabilities,
  NULL
};

static const _ExtendedGDBusMethodInfo _org_bluez_obex_session1_method_info_get_capabilities =
{
  {
    -1,
    (gchar *) "GetCapabilities",
    NULL,
    (GDBusArgInfo **) &_org_bluez_obex_session1_method_info_get_capabilities_OUT_ARG_pointers,
    NULL
  },
  "handle-get-capabilities",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _org_bluez_obex_session1_method_info_pointers[] =
{
  &_org_bluez_obex_session1_method_info_get_capabilities,
  NULL
};

static const _ExtendedGDBusPropertyInfo _org_bluez_obex_session1_property_info_source =
{
  {
    -1,
    (gchar *) "Source",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "source",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _org_bluez_obex_session1_property_info_destination =
{
  {
    -1,
    (gchar *) "Destination",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "destination",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _org_bluez_obex_session1_property_info_channel =
{
  {
    -1,
    (gchar *) "Channel",
    (gchar *) "y",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "channel",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _org_bluez_obex_session1_property_info_target =
{
  {
    -1,
    (gchar *) "Target",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "target",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _org_bluez_obex_session1_property_info_pointers[] =
{
  &_org_bluez_obex_session1_property_info_source,
  &_org_bluez_obex_session1_property_info_destination,
  &_org_bluez_obex_session1_property_info_channel,
  &_org_bluez_obex_session1_property_info_target,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _org_bluez_obex_session1_interface_info =
{
  {
    -1,
    (gchar *) "org.bluez.obex.Session1",
    (GDBusMethodInfo **) &_org_bluez_obex_session1_method_info_pointers,
    NULL,
    (GDBusPropertyInfo **) &_org_bluez_obex_session1_property_info_pointers,
    NULL
  },
  "org-bluez-obex-session1",
};


/**
 * org_bluez_obex_session1_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-bluez-obex-Session1.top_of_page">org.bluez.obex.Session1</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
org_bluez_obex_session1_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_org_bluez_obex_session1_interface_info.parent_struct;
}

/**
 * org_bluez_obex_session1_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #OrgBluezObexSession1 interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
org_bluez_obex_session1_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "source");
  g_object_class_override_property (klass, property_id_begin++, "destination");
  g_object_class_override_property (klass, property_id_begin++, "channel");
  g_object_class_override_property (klass, property_id_begin++, "target");
  return property_id_begin - 1;
}



/**
 * OrgBluezObexSession1:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-bluez-obex-Session1.top_of_page">org.bluez.obex.Session1</link>.
 */

/**
 * OrgBluezObexSession1Iface:
 * @parent_iface: The parent interface.
 * @handle_get_capabilities: Handler for the #OrgBluezObexSession1::handle-get-capabilities signal.
 * @get_channel: Getter for the #OrgBluezObexSession1:channel property.
 * @get_destination: Getter for the #OrgBluezObexSession1:destination property.
 * @get_source: Getter for the #OrgBluezObexSession1:source property.
 * @get_target: Getter for the #OrgBluezObexSession1:target property.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-bluez-obex-Session1.top_of_page">org.bluez.obex.Session1</link>.
 */

typedef OrgBluezObexSession1Iface OrgBluezObexSession1Interface;
G_DEFINE_INTERFACE (OrgBluezObexSession1, org_bluez_obex_session1, G_TYPE_OBJECT);

static void
org_bluez_obex_session1_default_init (OrgBluezObexSession1Iface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * OrgBluezObexSession1::handle-get-capabilities:
   * @object: A #OrgBluezObexSession1.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-bluez-obex-Session1.GetCapabilities">GetCapabilities()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call org_bluez_obex_session1_complete_get_capabilities() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-capabilities",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OrgBluezObexSession1Iface, handle_get_capabilities),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /* GObject properties for D-Bus properties: */
  /**
   * OrgBluezObexSession1:source:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-bluez-obex-Session1.Source">"Source"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("source", "Source", "Source", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OrgBluezObexSession1:destination:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-bluez-obex-Session1.Destination">"Destination"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("destination", "Destination", "Destination", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OrgBluezObexSession1:channel:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-bluez-obex-Session1.Channel">"Channel"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_uchar ("channel", "Channel", "Channel", 0, 255, 0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OrgBluezObexSession1:target:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-bluez-obex-Session1.Target">"Target"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("target", "Target", "Target", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * org_bluez_obex_session1_get_source: (skip)
 * @object: A #OrgBluezObexSession1.
 *
 * Gets the value of the <link linkend="gdbus-property-org-bluez-obex-Session1.Source">"Source"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use org_bluez_obex_session1_dup_source() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
org_bluez_obex_session1_get_source (OrgBluezObexSession1 *object)
{
  return ORG_BLUEZ_OBEX_SESSION1_GET_IFACE (object)->get_source (object);
}

/**
 * org_bluez_obex_session1_dup_source: (skip)
 * @object: A #OrgBluezObexSession1.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-bluez-obex-Session1.Source">"Source"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
org_bluez_obex_session1_dup_source (OrgBluezObexSession1 *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "source", &value, NULL);
  return value;
}

/**
 * org_bluez_obex_session1_set_source: (skip)
 * @object: A #OrgBluezObexSession1.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-bluez-obex-Session1.Source">"Source"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
org_bluez_obex_session1_set_source (OrgBluezObexSession1 *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "source", value, NULL);
}

/**
 * org_bluez_obex_session1_get_destination: (skip)
 * @object: A #OrgBluezObexSession1.
 *
 * Gets the value of the <link linkend="gdbus-property-org-bluez-obex-Session1.Destination">"Destination"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use org_bluez_obex_session1_dup_destination() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
org_bluez_obex_session1_get_destination (OrgBluezObexSession1 *object)
{
  return ORG_BLUEZ_OBEX_SESSION1_GET_IFACE (object)->get_destination (object);
}

/**
 * org_bluez_obex_session1_dup_destination: (skip)
 * @object: A #OrgBluezObexSession1.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-bluez-obex-Session1.Destination">"Destination"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
org_bluez_obex_session1_dup_destination (OrgBluezObexSession1 *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "destination", &value, NULL);
  return value;
}

/**
 * org_bluez_obex_session1_set_destination: (skip)
 * @object: A #OrgBluezObexSession1.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-bluez-obex-Session1.Destination">"Destination"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
org_bluez_obex_session1_set_destination (OrgBluezObexSession1 *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "destination", value, NULL);
}

/**
 * org_bluez_obex_session1_get_channel: (skip)
 * @object: A #OrgBluezObexSession1.
 *
 * Gets the value of the <link linkend="gdbus-property-org-bluez-obex-Session1.Channel">"Channel"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
guchar 
org_bluez_obex_session1_get_channel (OrgBluezObexSession1 *object)
{
  return ORG_BLUEZ_OBEX_SESSION1_GET_IFACE (object)->get_channel (object);
}

/**
 * org_bluez_obex_session1_set_channel: (skip)
 * @object: A #OrgBluezObexSession1.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-bluez-obex-Session1.Channel">"Channel"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
org_bluez_obex_session1_set_channel (OrgBluezObexSession1 *object, guchar value)
{
  g_object_set (G_OBJECT (object), "channel", value, NULL);
}

/**
 * org_bluez_obex_session1_get_target: (skip)
 * @object: A #OrgBluezObexSession1.
 *
 * Gets the value of the <link linkend="gdbus-property-org-bluez-obex-Session1.Target">"Target"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use org_bluez_obex_session1_dup_target() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
org_bluez_obex_session1_get_target (OrgBluezObexSession1 *object)
{
  return ORG_BLUEZ_OBEX_SESSION1_GET_IFACE (object)->get_target (object);
}

/**
 * org_bluez_obex_session1_dup_target: (skip)
 * @object: A #OrgBluezObexSession1.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-bluez-obex-Session1.Target">"Target"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
org_bluez_obex_session1_dup_target (OrgBluezObexSession1 *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "target", &value, NULL);
  return value;
}

/**
 * org_bluez_obex_session1_set_target: (skip)
 * @object: A #OrgBluezObexSession1.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-bluez-obex-Session1.Target">"Target"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
org_bluez_obex_session1_set_target (OrgBluezObexSession1 *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "target", value, NULL);
}

/**
 * org_bluez_obex_session1_call_get_capabilities:
 * @proxy: A #OrgBluezObexSession1Proxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-bluez-obex-Session1.GetCapabilities">GetCapabilities()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call org_bluez_obex_session1_call_get_capabilities_finish() to get the result of the operation.
 *
 * See org_bluez_obex_session1_call_get_capabilities_sync() for the synchronous, blocking version of this method.
 */
void
org_bluez_obex_session1_call_get_capabilities (
    OrgBluezObexSession1 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetCapabilities",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * org_bluez_obex_session1_call_get_capabilities_finish:
 * @proxy: A #OrgBluezObexSession1Proxy.
 * @out_capabilities: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to org_bluez_obex_session1_call_get_capabilities().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with org_bluez_obex_session1_call_get_capabilities().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_bluez_obex_session1_call_get_capabilities_finish (
    OrgBluezObexSession1 *proxy,
    gchar **out_capabilities,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_capabilities);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_bluez_obex_session1_call_get_capabilities_sync:
 * @proxy: A #OrgBluezObexSession1Proxy.
 * @out_capabilities: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-bluez-obex-Session1.GetCapabilities">GetCapabilities()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See org_bluez_obex_session1_call_get_capabilities() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_bluez_obex_session1_call_get_capabilities_sync (
    OrgBluezObexSession1 *proxy,
    gchar **out_capabilities,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetCapabilities",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_capabilities);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_bluez_obex_session1_complete_get_capabilities:
 * @object: A #OrgBluezObexSession1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @capabilities: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-bluez-obex-Session1.GetCapabilities">GetCapabilities()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
org_bluez_obex_session1_complete_get_capabilities (
    OrgBluezObexSession1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *capabilities)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(s)",
                   capabilities));
}

/* ------------------------------------------------------------------------ */

/**
 * OrgBluezObexSession1Proxy:
 *
 * The #OrgBluezObexSession1Proxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * OrgBluezObexSession1ProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #OrgBluezObexSession1Proxy.
 */

struct _OrgBluezObexSession1ProxyPrivate
{
  GData *qdata;
};

static void org_bluez_obex_session1_proxy_iface_init (OrgBluezObexSession1Iface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (OrgBluezObexSession1Proxy, org_bluez_obex_session1_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (OrgBluezObexSession1Proxy)
                         G_IMPLEMENT_INTERFACE (TYPE_ORG_BLUEZ_OBEX_SESSION1, org_bluez_obex_session1_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (OrgBluezObexSession1Proxy, org_bluez_obex_session1_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_ORG_BLUEZ_OBEX_SESSION1, org_bluez_obex_session1_proxy_iface_init));

#endif
static void
org_bluez_obex_session1_proxy_finalize (GObject *object)
{
  OrgBluezObexSession1Proxy *proxy = ORG_BLUEZ_OBEX_SESSION1_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (org_bluez_obex_session1_proxy_parent_class)->finalize (object);
}

static void
org_bluez_obex_session1_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  info = _org_bluez_obex_session1_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
org_bluez_obex_session1_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface org.bluez.obex.Session1: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
org_bluez_obex_session1_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  info = _org_bluez_obex_session1_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "org.bluez.obex.Session1", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) org_bluez_obex_session1_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
org_bluez_obex_session1_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_org_bluez_obex_session1_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_ORG_BLUEZ_OBEX_SESSION1);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_ORG_BLUEZ_OBEX_SESSION1);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
org_bluez_obex_session1_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  OrgBluezObexSession1Proxy *proxy = ORG_BLUEZ_OBEX_SESSION1_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_org_bluez_obex_session1_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_org_bluez_obex_session1_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static const gchar *
org_bluez_obex_session1_proxy_get_source (OrgBluezObexSession1 *object)
{
  OrgBluezObexSession1Proxy *proxy = ORG_BLUEZ_OBEX_SESSION1_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Source");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
org_bluez_obex_session1_proxy_get_destination (OrgBluezObexSession1 *object)
{
  OrgBluezObexSession1Proxy *proxy = ORG_BLUEZ_OBEX_SESSION1_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Destination");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static guchar 
org_bluez_obex_session1_proxy_get_channel (OrgBluezObexSession1 *object)
{
  OrgBluezObexSession1Proxy *proxy = ORG_BLUEZ_OBEX_SESSION1_PROXY (object);
  GVariant *variant;
  guchar value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Channel");
  if (variant != NULL)
    {
      value = g_variant_get_byte (variant);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
org_bluez_obex_session1_proxy_get_target (OrgBluezObexSession1 *object)
{
  OrgBluezObexSession1Proxy *proxy = ORG_BLUEZ_OBEX_SESSION1_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Target");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static void
org_bluez_obex_session1_proxy_init (OrgBluezObexSession1Proxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = org_bluez_obex_session1_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_ORG_BLUEZ_OBEX_SESSION1_PROXY, OrgBluezObexSession1ProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), org_bluez_obex_session1_interface_info ());
}

static void
org_bluez_obex_session1_proxy_class_init (OrgBluezObexSession1ProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = org_bluez_obex_session1_proxy_finalize;
  gobject_class->get_property = org_bluez_obex_session1_proxy_get_property;
  gobject_class->set_property = org_bluez_obex_session1_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = org_bluez_obex_session1_proxy_g_signal;
  proxy_class->g_properties_changed = org_bluez_obex_session1_proxy_g_properties_changed;

  org_bluez_obex_session1_override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (OrgBluezObexSession1ProxyPrivate));
#endif
}

static void
org_bluez_obex_session1_proxy_iface_init (OrgBluezObexSession1Iface *iface)
{
  iface->get_source = org_bluez_obex_session1_proxy_get_source;
  iface->get_destination = org_bluez_obex_session1_proxy_get_destination;
  iface->get_channel = org_bluez_obex_session1_proxy_get_channel;
  iface->get_target = org_bluez_obex_session1_proxy_get_target;
}

/**
 * org_bluez_obex_session1_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-bluez-obex-Session1.top_of_page">org.bluez.obex.Session1</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call org_bluez_obex_session1_proxy_new_finish() to get the result of the operation.
 *
 * See org_bluez_obex_session1_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
org_bluez_obex_session1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_ORG_BLUEZ_OBEX_SESSION1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.bluez.obex.Session1", NULL);
}

/**
 * org_bluez_obex_session1_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to org_bluez_obex_session1_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with org_bluez_obex_session1_proxy_new().
 *
 * Returns: (transfer full) (type OrgBluezObexSession1Proxy): The constructed proxy object or %NULL if @error is set.
 */
OrgBluezObexSession1 *
org_bluez_obex_session1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return ORG_BLUEZ_OBEX_SESSION1 (ret);
  else
    return NULL;
}

/**
 * org_bluez_obex_session1_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-bluez-obex-Session1.top_of_page">org.bluez.obex.Session1</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See org_bluez_obex_session1_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type OrgBluezObexSession1Proxy): The constructed proxy object or %NULL if @error is set.
 */
OrgBluezObexSession1 *
org_bluez_obex_session1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_ORG_BLUEZ_OBEX_SESSION1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.bluez.obex.Session1", NULL);
  if (ret != NULL)
    return ORG_BLUEZ_OBEX_SESSION1 (ret);
  else
    return NULL;
}


/**
 * org_bluez_obex_session1_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like org_bluez_obex_session1_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call org_bluez_obex_session1_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See org_bluez_obex_session1_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
org_bluez_obex_session1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_ORG_BLUEZ_OBEX_SESSION1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.bluez.obex.Session1", NULL);
}

/**
 * org_bluez_obex_session1_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to org_bluez_obex_session1_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with org_bluez_obex_session1_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type OrgBluezObexSession1Proxy): The constructed proxy object or %NULL if @error is set.
 */
OrgBluezObexSession1 *
org_bluez_obex_session1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return ORG_BLUEZ_OBEX_SESSION1 (ret);
  else
    return NULL;
}

/**
 * org_bluez_obex_session1_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like org_bluez_obex_session1_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See org_bluez_obex_session1_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type OrgBluezObexSession1Proxy): The constructed proxy object or %NULL if @error is set.
 */
OrgBluezObexSession1 *
org_bluez_obex_session1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_ORG_BLUEZ_OBEX_SESSION1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.bluez.obex.Session1", NULL);
  if (ret != NULL)
    return ORG_BLUEZ_OBEX_SESSION1 (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * OrgBluezObexSession1Skeleton:
 *
 * The #OrgBluezObexSession1Skeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * OrgBluezObexSession1SkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #OrgBluezObexSession1Skeleton.
 */

struct _OrgBluezObexSession1SkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_org_bluez_obex_session1_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_ORG_BLUEZ_OBEX_SESSION1);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_ORG_BLUEZ_OBEX_SESSION1);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_org_bluez_obex_session1_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_org_bluez_obex_session1_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_org_bluez_obex_session1_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_org_bluez_obex_session1_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _org_bluez_obex_session1_skeleton_vtable =
{
  _org_bluez_obex_session1_skeleton_handle_method_call,
  _org_bluez_obex_session1_skeleton_handle_get_property,
  _org_bluez_obex_session1_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
org_bluez_obex_session1_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return org_bluez_obex_session1_interface_info ();
}

static GDBusInterfaceVTable *
org_bluez_obex_session1_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_org_bluez_obex_session1_skeleton_vtable;
}

static GVariant *
org_bluez_obex_session1_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_org_bluez_obex_session1_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _org_bluez_obex_session1_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _org_bluez_obex_session1_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _org_bluez_obex_session1_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.bluez.obex.Session1", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _org_bluez_obex_session1_emit_changed (gpointer user_data);

static void
org_bluez_obex_session1_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _org_bluez_obex_session1_emit_changed (skeleton);
}

static void org_bluez_obex_session1_skeleton_iface_init (OrgBluezObexSession1Iface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (OrgBluezObexSession1Skeleton, org_bluez_obex_session1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (OrgBluezObexSession1Skeleton)
                         G_IMPLEMENT_INTERFACE (TYPE_ORG_BLUEZ_OBEX_SESSION1, org_bluez_obex_session1_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (OrgBluezObexSession1Skeleton, org_bluez_obex_session1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_ORG_BLUEZ_OBEX_SESSION1, org_bluez_obex_session1_skeleton_iface_init));

#endif
static void
org_bluez_obex_session1_skeleton_finalize (GObject *object)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (object);
  guint n;
  for (n = 0; n < 4; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (org_bluez_obex_session1_skeleton_parent_class)->finalize (object);
}

static void
org_bluez_obex_session1_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_org_bluez_obex_session1_emit_changed (gpointer user_data)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "org.bluez.obex.Session1",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_org_bluez_obex_session1_schedule_emit_changed (OrgBluezObexSession1Skeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
org_bluez_obex_session1_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _org_bluez_obex_session1_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _org_bluez_obex_session1_emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
org_bluez_obex_session1_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _org_bluez_obex_session1_schedule_emit_changed (skeleton, _org_bluez_obex_session1_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
org_bluez_obex_session1_skeleton_init (OrgBluezObexSession1Skeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = org_bluez_obex_session1_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_ORG_BLUEZ_OBEX_SESSION1_SKELETON, OrgBluezObexSession1SkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 4);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[1], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[2], G_TYPE_UCHAR);
  g_value_init (&skeleton->priv->properties[3], G_TYPE_STRING);
}

static const gchar *
org_bluez_obex_session1_skeleton_get_source (OrgBluezObexSession1 *object)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
org_bluez_obex_session1_skeleton_get_destination (OrgBluezObexSession1 *object)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[1]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static guchar 
org_bluez_obex_session1_skeleton_get_channel (OrgBluezObexSession1 *object)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (object);
  guchar value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_uchar (&(skeleton->priv->properties[2]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
org_bluez_obex_session1_skeleton_get_target (OrgBluezObexSession1 *object)
{
  OrgBluezObexSession1Skeleton *skeleton = ORG_BLUEZ_OBEX_SESSION1_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[3]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
org_bluez_obex_session1_skeleton_class_init (OrgBluezObexSession1SkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = org_bluez_obex_session1_skeleton_finalize;
  gobject_class->get_property = org_bluez_obex_session1_skeleton_get_property;
  gobject_class->set_property = org_bluez_obex_session1_skeleton_set_property;
  gobject_class->notify       = org_bluez_obex_session1_skeleton_notify;


  org_bluez_obex_session1_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = org_bluez_obex_session1_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = org_bluez_obex_session1_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = org_bluez_obex_session1_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = org_bluez_obex_session1_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (OrgBluezObexSession1SkeletonPrivate));
#endif
}

static void
org_bluez_obex_session1_skeleton_iface_init (OrgBluezObexSession1Iface *iface)
{
  iface->get_source = org_bluez_obex_session1_skeleton_get_source;
  iface->get_destination = org_bluez_obex_session1_skeleton_get_destination;
  iface->get_channel = org_bluez_obex_session1_skeleton_get_channel;
  iface->get_target = org_bluez_obex_session1_skeleton_get_target;
}

/**
 * org_bluez_obex_session1_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-bluez-obex-Session1.top_of_page">org.bluez.obex.Session1</link>.
 *
 * Returns: (transfer full) (type OrgBluezObexSession1Skeleton): The skeleton object.
 */
OrgBluezObexSession1 *
org_bluez_obex_session1_skeleton_new (void)
{
  return ORG_BLUEZ_OBEX_SESSION1 (g_object_new (TYPE_ORG_BLUEZ_OBEX_SESSION1_SKELETON, NULL));
}

